# Generated by Django 2.2.28 on 2022-07-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('eadresse', models.CharField(max_length=50)),
            ],
        ),
    ]
