# Generated by Django 4.0.6 on 2022-07-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_createc_delete_regist'),
    ]

    operations = [
        migrations.CreateModel(
            name='addproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.EmailField(max_length=100)),
                ('countinstock', models.TextField(blank=True, null=True)),
                ('imgurl', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('category', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
