# Generated by Django 4.0.6 on 2022-07-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_alter_addproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='countinstock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
