# Generated by Django 4.0.6 on 2022-07-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0005_alter_addproduct_countinstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='countinstock',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
