# Generated by Django 4.0.6 on 2022-08-16 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.addproduct')),
            ],
        ),
    ]
