# Generated by Django 4.0.6 on 2022-08-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0008_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='c',
        ),
    ]
