# Generated by Django 4.0.6 on 2022-08-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0009_remove_cartitems_c'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartitems',
        ),
    ]
