# Generated by Django 4.0.6 on 2022-08-17 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0010_delete_cartitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pquantity', models.IntegerField(default=0)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.addproduct')),
            ],
        ),
    ]
