# Generated by Django 4.0.6 on 2022-08-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0011_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='items',
        ),
    ]
