# Generated by Django 4.0.6 on 2022-08-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0012_delete_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=100)),
                ('pcategory', models.CharField(max_length=15)),
                ('pquantity', models.IntegerField(default=0)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.addproduct')),
            ],
        ),
    ]
