# Generated by Django 4.0.6 on 2022-08-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0013_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pname',
            field=models.CharField(max_length=100),
        ),
    ]
