# Generated by Django 4.0.6 on 2022-08-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0014_alter_item_pname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
