# Generated by Django 4.0.6 on 2022-08-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0015_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='it',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=100)),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=100)),
                ('pcategory', models.CharField(max_length=15)),
                ('pquantity', models.IntegerField(default=0)),
            ],
        ),
    ]
